version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3001"
    depends_on:
      - api-gateway

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  qdrant:
    image: qdrant/qdrant:v1.5.1
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  api-gateway:
    build:
      context: ..
      dockerfile: ./backend/services/gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:8000"
    depends_on:
      - ingestion-service
      - query-service

  ingestion-service:
    build:
      context: ..
      dockerfile: ./backend/services/ingestion/Dockerfile
    depends_on:
      - qdrant
      - postgres

  llm-router:
    build:
      context: ..
      dockerfile: ./backend/services/llm_router/Dockerfile
    ports:
      - "${LLM_PORT}:8004"

  embedding-service:
    build:
      context: ..
      dockerfile: ./backend/services/embedding/Dockerfile
    ports:
      - "${EMBEDDING_PORT}:8002"



volumes:
  postgres_data:
  qdrant_data: