services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db-auth
      - redis-auth
    networks:
      - backend-network

  db-auth:
    image: postgres:17-alpine
    container_name: jwt-auth-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - "5432:5432"

  redis-auth:
    image: redis:7-alpine
    container_name: jwt-auth-redis
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge
